name: Build
on: [push, pull_request, merge_group]
jobs:
  build:
    strategy:
      matrix:
        java: [17, 20]
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-java-${{ matrix.java }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-java-${{ matrix.java }}-gradle-
      - uses: actions/setup-java@v3
        with:
            distribution: temurin
            java-version: ${{ matrix.java }}
      - uses: gradle/wrapper-validation-action@v1
      # TODO - Go back to "--warning-mode=fail"
      - run: ./gradlew check build publishToMavenLocal --stacktrace --warning-mode=all -Porg.gradle.parallel.threads=4
      - uses: Juuxel/publish-checkstyle-report@v1
        if: ${{ failure() }}
        with:
          reports: |
            **/build/reports/checkstyle/*.xml
      # TODO - Re-enable once issues with Quilt Loader are solved
      # - run: mkdir run && echo "eula=true" >> run/eula.txt
      # - run: ./gradlew runAutoTestServer --stacktrace --warning-mode=fail
      - run: ./gradlew --stop
      - uses: actions/upload-artifact@v3
        with:
          name: Artifacts
          path: |
            build/libs/
            ./*/build/libs/
      - uses: actions/upload-artifact@v3
        with:
          name: Maven Local
          path: /home/runner/.m2/repository

  #client_test:
  #  runs-on: ubuntu-22.04
  #  steps:
  #    - uses: actions/checkout@v3
  #      with:
  #        fetch-depth: 0
  #    - uses: actions/setup-java@v3
  #      with:
  #        distribution: temurin
  #        java-version: 17
  #    - name: Run Auto test Client
  #      uses: modmuss50/xvfb-action@v1
  #      with:
  #        run: ./gradlew runProductionAutoTestClient --stacktrace --warning-mode=fail
  #    - uses: actions/upload-artifact@v3
  #      if: always()
  #      with:
  #        name: Test Screenshots
  #        path: run/screenshots
  #
  #server_test:
  #  runs-on: ubuntu-22.04
  #  steps:
  #    - uses: actions/checkout@v3
  #      with:
  #        fetch-depth: 0
  #    - uses: actions/setup-java@v3
  #      with:
  #        distribution: temurin
  #        java-version: 17
  #    - run: mkdir run && echo "eula=true" >> run/eula.txt
  #    - run: ./gradlew runProductionAutoTestServer --stacktrace --warning-mode=fail

  # check_resources:
  #   runs-on: ubuntu-22.04
  #   steps:
  #     - uses: actions/checkout@v3
  #       with:
  #         fetch-depth: 0
  #     - uses: actions/setup-java@v3
  #       with:
  #         distribution: temurin
  #         java-version: 17
  #     - run: ./gradlew generateResources --stacktrace --warning-mode=fail
  #     - run: if [ -n "$(git status --porcelain)" ]; then exit 1; fi
