name: Build
on: [push, pull_request]
jobs:
  build:
    strategy:
      matrix:
        java: [17, 18]
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-java-${{ matrix.java }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-java-${{ matrix.java }}-gradle-
      - uses: actions/setup-java@v3
        with:
            distribution: temurin
            java-version: ${{ matrix.java }}
      - uses: gradle/wrapper-validation-action@v1
      # TODO - Re-enable once issues with Quilt Loader are solved
      # - run: ./gradlew check build publishToMavenLocal --stacktrace --warning-mode=fail -Porg.gradle.parallel.threads=4
      - run: ./gradlew build publishToMavenLocal --stacktrace --warning-mode=fail -Porg.gradle.parallel.threads=4
      - uses: Juuxel/publish-checkstyle-report@v1
        if: ${{ failure() }}
        with:
          reports: |
            **/build/reports/checkstyle/*.xml
      # - run: mkdir run && echo "eula=true" >> run/eula.txt
      # - run: ./gradlew runAutoTestServer --stacktrace --warning-mode=fail
      - run: ./gradlew --stop
      - uses: actions/upload-artifact@v3
        with:
          name: Artifacts
          path: |
            build/libs/
            ./*/build/libs/
      - uses: actions/upload-artifact@v3
        with:
          name: Maven Local
          path: /home/runner/.m2/repository
